### ISSUE TITLE
Errors with i3nagbar

### ISSUE THREAD

**Issue by richardtkemp** [proxypoke/quickswitch-for-i3#19]
How to trigger:
Edit i3 config file to include an error and restart i3. Observe the red nagbar offering to show errors or edit the config file - don't make any choices on the nagbar. Now start quickswitch. I receive the following response:

Traceback (most recent call last):
  File "/home/rich/bin/quickswitch.py", line 259, in <module>
    main()
  File "/home/rich/bin/quickswitch.py", line 250, in main
    lookup = lookup_func()
  File "/home/rich/bin/quickswitch.py", line 62, in get_windows
    return create_lookup_table(windows)
  File "/home/rich/bin/quickswitch.py", line 147, in create_lookup_table
    if name.startswith("i3bar for output"):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by OliverUv** [comment]
Hi! Proxypoke hasn't got time to maintain quickswitch, so at the moment my fork is (probably) the most complete. I've pulled in a lot of the other forks' improvements. My fork is at https://github.com/OliverUv/quickswitch-for-i3

**Comment by richardtkemp** [comment]
Thanks for letting me know Oliver, I will try it out soon.
