### ISSUE TITLE
Error while launching quickswitch

### ISSUE THREAD

**Issue by msx** [proxypoke/quickswitch-for-i3#23]
Hi!

Today I found quickswitch wasn't working, launching it from console shows this:
$ quickswitch.py 
Traceback (most recent call last):
  File "/usr/bin/quickswitch.py", line 247, in <module>
    main()
  File "/usr/bin/quickswitch.py", line 238, in main
    lookup = lookup_func()
  File "/usr/bin/quickswitch.py", line 65, in get_windows
    return create_lookup_table(windows)
  File "/usr/bin/quickswitch.py", line 147, in create_lookup_table
    if name.startswith("i3bar for output"):
AttributeError: 'NoneType' object has no attribute 'startswith'

Originally I installed quickswitch via pip and was working great (well, with the exception of bug #21) and all of a sudden it stopped working - presumably because a system update to the Python stack?
Running a 'pip install quickswitch --upgrade' tells me I already have latest quickswitch version.
My system is an F21, fully updated.

**Comment by msx** [comment]
*UPDATE*
The problem has definitely to be with the Python libraries installed in my system - or with the package uploaded to pip; cloning the repository and compiling quickswitch-i3 produces a working copy of it.
I'm closing this ticket for now then.
Cheers.
